"""Detection signals.

Signal identities are fixed in planning.md (§1):
  - Signal 1 — Burstiness (local, deterministic).      [built in M4]
  - Signal 2 — Stylometric LLM judge (Groq).           [built here in M3]

Each signal emits an AI-likelihood in [0, 1] (0 = looks human, 1 = looks AI),
plus an `ok` flag so the scorer can treat a failed call as "no signal" rather
than as "human".
"""

import json
import os
import re
import statistics

from groq import Groq

GROQ_MODEL = "llama-3.3-70b-versatile"

# --- Signal 1: Burstiness (local, deterministic) -----------------------------
# planning.md §1: score_b = clamp((0.70 - cv) / (0.70 - 0.30), 0, 1)
# cv = stdev(sentence word-counts) / mean. High cv (bursty) -> human -> low score.
_CV_HUMAN = 0.70   # cv at/above this -> 0.0 (very human)
_CV_AI = 0.30      # cv at/below this -> 1.0 (very AI)
_SENTENCE_SPLIT = re.compile(r"[.!?]+(?:\s+|$)")


def burstiness(text: str) -> dict:
    """Signal 1 (built in M4): sentence-length variability.

    Returns {"score": float in [0,1], "stats": {n_sentences, mean_len,
    stdev_len, cv}}. With fewer than 2 sentences cv is undefined, so the score is
    neutral (0.5) and the low n_sentences lets the confidence length-gate take over.
    """
    sentences = [s for s in _SENTENCE_SPLIT.split(text) if s.strip()]
    lengths = [len(s.split()) for s in sentences]
    n = len(lengths)

    if n < 2:
        return {
            "score": 0.5,
            "stats": {
                "n_sentences": n,
                "mean_len": float(lengths[0]) if lengths else 0.0,
                "stdev_len": 0.0,
                "cv": None,
            },
        }

    mean_len = statistics.mean(lengths)
    stdev_len = statistics.stdev(lengths)  # sample stdev
    cv = stdev_len / mean_len if mean_len else 0.0
    score = max(0.0, min(1.0, (_CV_HUMAN - cv) / (_CV_HUMAN - _CV_AI)))
    return {
        "score": round(score, 4),
        "stats": {
            "n_sentences": n,
            "mean_len": round(mean_len, 2),
            "stdev_len": round(stdev_len, 2),
            "cv": round(cv, 4),
        },
    }

_client = None


def _get_client():
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set")
        _client = Groq(api_key=api_key)
    return _client


_SYSTEM_PROMPT = (
    "You are a forensic text analyst estimating the probability that a passage "
    "was generated by a large language model rather than written by a human. "
    "Judge style, not subject matter or correctness. Signals of machine text "
    "include: formulaic transitions (e.g. 'Moreover', 'In conclusion'), evenly "
    "distributed hedging, polished-but-generic register, and an absence of "
    "specific lived or idiosyncratic detail. Signals of human text include "
    "uneven rhythm, concrete personal detail, and idiosyncrasy. IMPORTANT: do "
    "not penalize a passage merely for being formal or for reading like "
    "non-native English — those are common in genuine human writing and must "
    "not by themselves raise the AI estimate. When unsure, stay near 0.5. "
    "Respond ONLY with a JSON object of the form "
    '{"ai_likelihood": <float 0..1>, "rationale": "<one sentence>"}.'
)


def stylometric_signal(text: str) -> dict:
    """Signal 2 (built first in M3): LLM stylometric judge via Groq.

    Returns {"score": float in [0,1], "rationale": str, "ok": bool}.
    On any failure (no key, network, timeout, bad JSON) returns ok=False so the
    caller can fall back rather than mistaking failure for a "human" verdict.
    """
    try:
        client = _get_client()
        resp = client.chat.completions.create(
            model=GROQ_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": f"Assess this passage:\n\n{text}"},
            ],
            response_format={"type": "json_object"},
            temperature=0,
            timeout=20.0,
        )
        data = json.loads(resp.choices[0].message.content)
        score = max(0.0, min(1.0, float(data["ai_likelihood"])))
        rationale = str(data.get("rationale", ""))[:500]
        return {"score": score, "rationale": rationale, "ok": True}
    except Exception as exc:  # noqa: BLE001 — any failure means "no signal"
        return {"score": 0.0, "rationale": f"signal unavailable: {exc}", "ok": False}
